-- AlterTable
ALTER TABLE "Coupon" ALTER COLUMN "firstValue" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "usedValue" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "restValue" SET DATA TYPE DECIMAL(65,30);
